from typing import Any

import httpx

from config import get_settings


class LLMClient:
    def __init__(self) -> None:
        self.settings = get_settings()
        self._client = httpx.AsyncClient(timeout=self.settings.LLM_TIMEOUT_SECONDS)

    async def _request(self, payload: dict[str, Any]) -> str:
        url = self.settings.LLM_BASE_URL
        headers = {
            "Authorization": f"Bearer {self.settings.LLM_API_KEY}",
            "Content-Type": "application/json",
        }

        last_exc: Exception | None = None
        for _ in range(self.settings.LLM_MAX_RETRIES):
            try:
                resp = await self._client.post(url, json=payload, headers=headers)
                resp.raise_for_status()
                data = resp.json()
                # здесь нужно подстроить под формат Cloud.ru
                return data.get("result") or data.get("choices", [{}])[0].get("text", "")
            except Exception as exc:
                last_exc = exc
        raise RuntimeError(f"LLM request failed: {last_exc}")

    async def generate(self, prompt: str) -> str:
        payload = {
            "messages": [
                {
                    "role": "system",
                    "content": "Ты QA-инженер, генерируешь тест-кейсы и автотесты на Python.",
                },
                {"role": "user", "content": prompt},
            ],
            "temperature": self.settings.LLM_TEMPERATURE,
            "max_tokens": self.settings.LLM_MAX_TOKENS,
        }
        try:
            return await self._request(payload)
        except Exception:
            return self._fallback_test()

    @staticmethod
    def _fallback_test() -> str:
        return (
            "import allure\n\n"
            "class TestFallback:\n"
            "    @allure.feature('fallback')\n"
            "    @allure.story('fallback')\n"
            "    @allure.title('Fallback test')\n"
            "    @allure.tag('LOW')\n"
            "    @allure.label('owner', 'autogenerated')\n"
            "    def test_fallback(self):\n"
            "        with allure.step('Arrange'):\n"
            "            x = 1\n"
            "        with allure.step('Act'):\n"
            "            y = x + 1\n"
            "        with allure.step('Assert'):\n"
            "            assert y == 2\n"
        )


llm_client = LLMClient()
