import re
from typing import Any

from llm_client import llm_client


def _extract_python_code(text: str) -> str:
    code = re.sub(r"``````", "")
    return code.strip()


async def generate_testcase(
    test_type: str,
    requirements_text: str | None = None,
    openapi_spec: Any | None = None,
) -> str:
    if not requirements_text and not openapi_spec:
        raise ValueError("Either requirements_text or openapi_spec must be provided")

    if openapi_spec is not None:
        req = f"OpenAPI спецификация: {openapi_spec}"
    else:
        req = requirements_text or ""

    priority = "CRITICAL" if test_type == "api" else "NORMAL"

    prompt = f"""
Ты --- AI-ассистент для генерации тест-кейсов в формате Allure TestOps as Code (Python).

Требования:
{req}

Сгенерируй код тест-кейса по паттерну AAA (Arrange-Act-Assert).

Обязательные декораторы Allure:
- @allure.feature
- @allure.story
- @allure.title
- @allure.tag ({priority})
- @allure.label("owner", "autogenerated")

Формат:

class TestClassName:
    @allure.title("...")
    def test_method(self):
        with allure.step("Arrange"): ...
        with allure.step("Act"): ...
        with allure.step("Assert"): ...

Код должен быть готов к запуску в pytest.
"""

    raw = await llm_client.generate(prompt)
    code = _extract_python_code(raw)

    if "import allure" not in code:
        code = "import allure\n\n" + code
    return code
import re
from typing import Any

from llm_client import llm_client


def _extract_python_code(text: str) -> str:
    code = re.sub(r"``````", "")
    return code.strip()


async def generate_testcase(
    test_type: str,
    requirements_text: str | None = None,
    openapi_spec: Any | None = None,
) -> str:
    if not requirements_text and not openapi_spec:
        raise ValueError("Either requirements_text or openapi_spec must be provided")

    if openapi_spec is not None:
        req = f"OpenAPI спецификация: {openapi_spec}"
    else:
        req = requirements_text or ""

    priority = "CRITICAL" if test_type == "api" else "NORMAL"

    prompt = f"""
Ты --- AI-ассистент для генерации тест-кейсов в формате Allure TestOps as Code (Python).

Требования:
{req}

Сгенерируй код тест-кейса по паттерну AAA (Arrange-Act-Assert).

Обязательные декораторы Allure:
- @allure.feature
- @allure.story
- @allure.title
- @allure.tag ({priority})
- @allure.label("owner", "autogenerated")

Формат:

class TestClassName:
    @allure.title("...")
    def test_method(self):
        with allure.step("Arrange"): ...
        with allure.step("Act"): ...
        with allure.step("Assert"): ...

Код должен быть готов к запуску в pytest.
"""

    raw = await llm_client.generate(prompt)
    code = _extract_python_code(raw)

    if "import allure" not in code:
        code = "import allure\n\n" + code
    return code
